### ISSUE TITLE
ShadowCastingMode does not exist

### ISSUE THREAD

**Issue by mluyties** [TheSniperFan/unityserializer-ng#10]
Hi SniperFan,

Thanks for taking this project over. I just imported your newest version and am receiving this error before I even touch anything:

Assets/Plugins/OpenUnityTools/unityserializer-ng/Serialization/UnitySerializationExtensions.cs(807,38): error CS0234: The type or namespace name `ShadowCastingMode' does not exist in the namespace `UnityEngine.Rendering'. Are you missing an assembly reference?

I am using Unity 4.6.1

Thanks,
Mike

**Comment by TheSniperFan** [comment]
Unity 5 only. Check out this fork. [brainz80/unityserializer-ng](https://github.com/brainz80/unityserializer-ng)

**Comment by mluyties** [comment]
Hi SniperFan,

I don't have access to Unity 5. Is the fork that you linked supposed to
work with 4.6?


Thanks,
Mike


On Mon, Jan 19, 2015 at 5:45 AM, TheSniperFan <notifications@github.com>
wrote:

> Closed #10 <https://github.com/TheSniperFan/unityserializer-ng/issues/10>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TheSniperFan/unityserializer-ng/issues/10#event-220977830>
> .
>



-- 
Sincerely,
Mike Luyties, CEO of RenterMonsters.com
www.rentermonsters.com
<http://www.rentermonsters.com>

**Comment by TheSniperFan** [comment]
[Right on top](https://github.com/brainz80/unityserializer-ng#what-is-unityserializer-ng)
